checks:
    php:
        code_rating: true
        duplication: true
filter:
    paths: [ 'src/*' ]

tools:
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true
build:
    environment:
        php: '7.1'
        php: '7.2'
